spring:
  data:
    mongodb:
      uri: ${WORKFLOW_MONGODB_URI}
      database: ${WORKFLOW_MONGODB_DATABASE}
      auto-index-creation: false

workflow:
  persistence:
    provider: mongodb

management:
  health:
    mongo:
      enabled: true
