spring:
  application:
    name: workflow-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  profiles:
    default: fake

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

server:
  error:
    include-message: never
    include-stacktrace: never
